name: Build Web3J integration

on:
  push:
    branches: [ main, develop ]

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up java
        uses: actions/setup-java@v2
        with:
          check-latest: true

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and report code coverage
        run: mvn -B clean install jacoco:report coveralls:report
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
